# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5f2d3f1799dc3c4585510b36ff07d7f0a97961199f833629c796376ce43ebfc6c589fd361fd636f3f921f0136438ae1f6d5865f8c63ee2d64103d55fe8819ae

test:
  secret_key_base: 28dac45bdc82fc738e40daffee7b0588ef3be86ea66cc73ed1ddd835bb967d12e67b931968f978d3ad8b0e1ba111f5146aff947d5b0c51c74ca75f86453c4f47

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
